<a href="https://colab.research.google.com/github/mmartigani/MachineLearning2/blob/main/ML10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [47]:
import time
import numpy as np
import pandas as pd

In [2]:
my_array =np.array([1,2,3,4,5])
my_array

array([1, 2, 3, 4, 5])

In [3]:
lista_grande = list(range(1000000))
array_grande= np.array(lista_grande)

In [4]:
inicio_lista= time.time()
for i in lista_grande:
  i **2
fin_lista = time.time()
print("Tiempo", fin_lista -inicio_lista)

Tiempo 0.6796319484710693


In [5]:
inicio_array=time.time()
array_grande **2
fin_array = time.time()
print("tiempo: ", fin_array-inicio_array)

tiempo:  0.0364985466003418


In [6]:
array= np.array([1,2,3])
array

array([1, 2, 3])

In [7]:
len(array)

3

In [8]:
array.shape

(3,)

In [9]:
array_2d= np.array([[1,2,3],[4,5,6]])
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
len(array_2d)

2

In [11]:
array_2d.shape

(2, 3)

In [12]:
x=[1,2,3]
y=[1,2,3]
z= [1,2,3]

In [13]:
np.concatenate([x,y,z])

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [14]:
a=[[1,2], [3,4]]
b=[[5,6],[7,8]]
np.concatenate([a,b], axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [15]:
a=[[1,2], [3,4]]
b=[[5,6],[7,8]]
np.concatenate([a,b], axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [16]:
array_reformado= np.concatenate([a,b],axis=0)
array_reformado

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [17]:
array_reformado = array_reformado .reshape(2,4)
array_reformado

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
array_sumado = array_reformado + array_reformado
array_sumado

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [19]:
array_multi = array_reformado * array_reformado
array_multi

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [20]:
raices =np.sqrt(array_multi)
raices

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [21]:
array1d=np.array([1,2,3,4,5])
array1d

array([1, 2, 3, 4, 5])

In [22]:
array2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
array2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
array1d[0]

1

In [24]:
array2d[0]

array([1, 2, 3])

In [25]:
array2d[1][2]

6

In [26]:
array1d[1:4]

array([2, 3, 4])

In [27]:
array2d[1,:]

array([4, 5, 6])

In [28]:
array2d[1,1:3]

array([5, 6])

In [29]:
array2d[:,1]

array([2, 5, 8])

In [30]:
array2d[:2,:2]

array([[1, 2],
       [4, 5]])

In [31]:
array2d >3

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [32]:
array2d %2 ==0

array([[False,  True, False],
       [ True, False,  True],
       [False,  True, False]])

In [33]:
array =np.array([1,2,3,4,5,6,7,8,9])
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
array.shape

(9,)

In [35]:
array_mod=array.reshape(3,3)
array_mod

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
array_mod2=array.reshape(-1,3)
array_mod2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
array_traspuesto = array_mod2.transpose()
array_traspuesto

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [38]:
array_chato = array_mod.flatten()
array_chato

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
array_ravel = array_mod.ravel()
array_ravel

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
array=np.array([1,2, np.nan, 4,5])
array

array([ 1.,  2., nan,  4.,  5.])

In [41]:
np.isnan(array)

array([False, False,  True, False, False])

In [42]:
np.nanmean(array)

3.0

In [43]:
array_con_0=np.where(np.isnan(array),0,array)
array_con_0

array([1., 2., 0., 4., 5.])

In [44]:
pro=np.nanmean(array)
array_promedio=np.where(np.isnan(array), pro,array)
array_promedio

array([1., 2., 3., 4., 5.])

In [45]:
array_sin_nan = array[~np.isnan(array)]
array_sin_nan

array([1., 2., 4., 5.])

In [48]:
m=pd.read_csv('/content/datos_meteorologicos.csv')
m

Fecha  Temperatura  Precipitación    Humedad
0     01/01/2010    17.440675      10.957482  52.384637
1     02/01/2010    25.759468       5.315628  30.633530
2     03/01/2010    20.138169      15.317706  41.496715
3     04/01/2010    17.244159      13.151008  90.684704
4     05/01/2010    11.182740      16.413667  22.116422
...          ...          ...            ...        ...
5105  24/12/2023    -9.554692      12.700998  50.094533
5106  25/12/2023     2.837831       5.475686  92.456057
5107  26/12/2023    29.873597       4.615012  18.362847
5108  27/12/2023          NaN            NaN        NaN
5109  28/12/2023    37.308043       7.330510  50.646211

[5110 rows x 4 columns]

In [50]:
m.head(2)

Fecha  Temperatura  Precipitación    Humedad
0  01/01/2010    17.440675      10.957482  52.384637
1  02/01/2010    25.759468       5.315628  30.633530

In [51]:
m.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Fecha          5110 non-null   object 
 1   Temperatura    4855 non-null   float64
 2   Precipitación  4855 non-null   float64
 3   Humedad        4855 non-null   float64
dtypes: float64(3), object(1)
memory usage: 159.8+ KB


In [52]:
m.describe()

Temperatura  Precipitación      Humedad
count  4855.000000    4855.000000  4855.000000
mean     14.889296       9.901604    54.359061
std      14.440466       5.801842    26.096345
min      -9.996378       0.003008    10.014980
25%       2.651777       4.756907    31.866578
50%      14.693274       9.853698    54.254478
75%      27.381451      14.966997    77.029500
max      39.998201      19.999559    99.996582

In [53]:
t=m['Temperatura'].to_numpy()
p=m['Precipitación'].to_numpy()
h=m['Humedad'].to_numpy()

In [54]:
t

array([17.4406752 , 25.75946832, 20.1381688 , ..., 29.87359717,
               nan, 37.30804318])

In [55]:
p

array([10.957482  ,  5.31562765, 15.31770609, ...,  4.61501177,
               nan,  7.33051023])

In [56]:
h

array([52.38463749, 30.63352983, 41.49671458, ..., 18.36284738,
               nan, 50.64621058])

In [58]:
t_nula = np.isnan(t)
p_nula = np.isnan(p)
h_nula = np.isnan(h)

In [59]:
t_nula

array([False, False, False, ..., False,  True, False])

In [60]:
p_nula

array([False, False, False, ..., False,  True, False])

In [61]:
h_nula

array([False, False, False, ..., False,  True, False])

In [62]:
t_promedio= np.nanmean(t)
p_promedio= np.nanmean(p)
h_promedio= np.nanmean(h)

In [63]:
t_promedio

14.889295723531715

In [64]:
p_promedio

9.9016035987084

In [65]:
h_promedio

54.35906079674394

In [66]:
t[t_nula]=t_promedio
p[p_nula]=p_promedio
h[h_nula]=h_promedio

In [67]:
t

array([17.4406752 , 25.75946832, 20.1381688 , ..., 29.87359717,
       14.88929572, 37.30804318])

In [69]:
p_total = np.sum(p)
p_total

50597.19438939993

In [70]:
h_max=np.max(h)
h_max

99.99658156071747

In [71]:
mas_calor= np.max(t)
mas_calor

39.99820092713012

In [72]:
resgistro_calor = np.where(t==mas_calor)[0][0]
resgistro_calor

2749

In [73]:
fecha_calurosa =m.iloc[resgistro_calor]['Fecha']
fecha_calurosa

'12/07/2017'

In [74]:
fecha_fria = m.iloc[np.where(t==np.min(t))[0][0]]['Fecha']
fecha_fria

'23/07/2020'

In [75]:
resultado = pd.DataFrame({'Metrica':['t_promedio','p_total','h_max','fecha_calurosa','fecha_fria'],
                          "valor":[t_promedio,p_total,h_max,fecha_calurosa,fecha_fria]})
resultado.to_csv('Analisis Meteorologicos.csv',index=False)