<a href="https://colab.research.google.com/github/mmartigani/MachineLearning2/blob/main/ML29.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import random
import time
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.preprocessing import MinMaxScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.datasets import load_iris
from sklearn.datasets import load_digits
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.models import Model
import tensorflow as tf
from scipy.cluster.hierarchy import dendrogram , linkage

In [3]:
dimensiones=(5,5)
estado_inicial=(0,0)
estado_objetivo=(4,4)
obstaculos = [(1,1),(1,3),(2,3),(3,0)]
acciones =[(-1,0), (1,0),(0,-1),(1,0  )]

In [4]:
num_dimensiones= dimensiones[0] * dimensiones [1]
num_dimensiones

25

In [5]:
num_acciones = len(acciones)
num_acciones

4

In [6]:
Q= np.zeros((num_dimensiones,num_acciones))
Q

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
def estado_a_indice(estado):
  return estado[0]*dimensiones[1]+estado[1]

In [10]:
ejemplo = estado_a_indice((1,0))
ejemplo

5

In [11]:
alpha = 0.1
gamma = 0.99
epsilon = 0.2
episodios = 100

In [17]:
def elegir_accion(estado):
  if random.uniform(0,1)< epsilon:
    return random.choice(range(num_acciones))
  else:
    return np.argmax(Q[estado_a_indice(estado)])

In [18]:
def aplicar_accion(estado,accion_idx):
  accion = acciones[accion_idx]
  nuevo_estado=tuple(np.add(estado,accion)% dimensiones)

  if nuevo_estado in obstaculos or nuevo_estado == estado:
    return estado, -100, False
  if nuevo_estado == estado_objetivo:
    return nuevo_estado , 100, True
  return nuevo_estado, -1 ,False

In [20]:
for episodio in range(episodios):
  estado= estado_inicial
  terminado=False

  while not terminado:
    idx_estado = estado_a_indice(estado)
    accion_idx= elegir_accion(estado)
    nuevo_estado, recompensa, terminado = aplicar_accion(estado, accion_idx)
    idx_nuevo_estado = estado_a_indice(nuevo_estado)

    Q[idx_estado, accion_idx]=Q[idx_estado, accion_idx] + alpha + (recompensa + gamma * np.max(Q[idx_nuevo_estado])- Q [idx_estado, accion_idx])
    estado = nuevo_estado

In [21]:
politica = np.zeros(dimensiones, dtype=int)
politica

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [22]:
for i in range(dimensiones[0]):
  for j in range(dimensiones [1]):
    estado=(i,j)
    idx_estado=estado_a_indice(estado)
    mejor_accion = np.argmax(Q[idx_estado])
    politica[i,j]=mejor_accion
print('Politica Aprendida : 0=arriba , 1=abajo, 2=inquierda, 3=derecha')
print(politica)

Politica Aprendida : 0=arriba , 1=abajo, 2=inquierda, 3=derecha
[[0 2 3 0 0]
 [0 0 2 0 0]
 [0 2 2 0 0]
 [0 0 3 3 1]
 [2 2 1 2 0]]
